version: '3.8'
services:
  postgres:
    image: postgres:15.4
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
